[package]
name = "rust-preq"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
bs58 = "0.5.1"
solana-client = "2.2.4"
solana-program = "2.2.1"
solana-sdk = "2.2.1"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
